# Generated by Django 3.2.19 on 2023-07-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
