# Generated by Django 3.2.19 on 2023-06-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image',
        ),
    ]
