# Generated by Django 3.2.19 on 2023-06-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0002_alter_discountcode_discount'),
        ('checkout', '0005_rename_original_bag_order_original_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount_codes.discountcode'),
        ),
    ]
