# Generated by Django 3.2.19 on 2023-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_discount_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
