# Generated by Django 3.2.19 on 2023-06-10 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
