# Generated by Django 3.2.19 on 2023-05-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'Condition'},
        ),
    ]
