# Generated by Django 3.2.19 on 2023-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230528_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='display_name',
            field=models.CharField(default='platform', max_length=254),
            preserve_default=False,
        ),
    ]
